### ISSUE TITLE
Hive Cluster Abyss

### ISSUE THREAD

**Issue by Moffein** [FMRadio11/StageAesthetic#2]
Hive Cluster Abyss looks great, but it's really dark and hard to see stuff. In this pic, the Elder Lemurian practically blends into the wall. Would you be able to brighten it up?
![20220122143642_1](https://user-images.githubusercontent.com/22742925/150656272-7f42655f-a852-4b7e-8795-5356f2913110.jpg)

**Comment by FMRadio11** [comment]
Hopefully fixed once 0.2.1 uploads fully. Thanks for pointing this out, I've tried to fix fog opacity when reintroducing ColorGrading but this was far from the only stage to end up too dark
