### ISSUE TITLE
when will it get updated for DLC?

### ISSUE THREAD

**Issue by ZANdewanai** [FMRadio11/StageAesthetic#4]
kinda want to see how they would look

**Comment by ZANdewanai** [comment]
also maybe some debugging to find out why it doesnt spawn interactables on sunset versions of the map, doesnt seem it giving the game the promp to spend money in them and well, the game not knowing where to spawn you// or just disabling them for now and updating the mod just with that so is playable

**Comment by hifoomin** [comment]
Updated version here: https://thunderstore.io/package/HIFU/StageAesthetic/

**Comment by ZANdewanai** [comment]
neato~
